create extension if not exists pgcrypto;

create table if not exists students (
  id bigint generated by default as identity primary key,
  student_name text not null,
  parent_name text,
  phone text,
  whatsapp text,
  instrument text check (instrument in ('guitar','piano','vocal')) default 'guitar',
  format text check (format in ('home','online')) default 'home',
  area text,
  address text,
  pincode text,
  maps_link text,
  start_date date,
  status text check (status in ('active','paused','inactive')) default 'active',
  fee_per_package numeric default 0,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists packages (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  package_title text not null,
  topic_focus text,
  total_classes integer default 8,
  used_classes integer default 0,
  remaining_classes integer default 8,
  amount numeric default 0,
  start_date date,
  status text check (status in ('active','completed','paused','cancelled')) default 'active',
  payment_status text check (payment_status in ('paid','pending','overdue')) default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists classes (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  package_id bigint references packages(id) on delete set null,
  class_date date not null,
  class_time text,
  status text check (status in ('completed','missed','rescheduled')) default 'completed',
  note text,
  parent_update_sent boolean default false,
  created_at timestamptz default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  package_id bigint references packages(id) on delete set null,
  amount numeric default 0,
  status text check (status in ('paid','pending','overdue','cancelled')) default 'pending',
  payment_method text check (payment_method in ('upi','bank','cash','other')) default 'upi',
  payment_date date,
  payment_link text,
  payment_title text,
  payment_note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists route_logs (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  class_id bigint references classes(id) on delete set null,
  visit_date date,
  area text,
  route_order integer default 1,
  distance_km numeric default 0,
  fuel_cost numeric default 0,
  travel_time_minutes integer default 0,
  created_at timestamptz default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  package_id bigint references packages(id) on delete set null,
  class_id bigint references classes(id) on delete set null,
  message_type text check (message_type in ('class_update','renewal_reminder','payment_link','manual_note')),
  message_text text,
  sent_to text,
  sent_status text default 'draft',
  created_at timestamptz default now()
);

create table if not exists schedule_events (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  package_id bigint references packages(id) on delete set null,
  event_type text check (event_type in ('class','payment','reminder')) default 'class',
  title text,
  event_date date not null,
  event_time text,
  duration_minutes integer default 60,
  status text check (status in ('scheduled','completed','missed','rescheduled','cancelled','paid','pending','overdue')) default 'scheduled',
  area text,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table students enable row level security;
alter table packages enable row level security;
alter table classes enable row level security;
alter table payments enable row level security;
alter table route_logs enable row level security;
alter table messages enable row level security;
alter table schedule_events enable row level security;

drop policy if exists "public all students" on students;
drop policy if exists "public all packages" on packages;
drop policy if exists "public all classes" on classes;
drop policy if exists "public all payments" on payments;
drop policy if exists "public all route_logs" on route_logs;
drop policy if exists "public all messages" on messages;
drop policy if exists "public all schedule_events" on schedule_events;

create policy "public all students" on students for all using (true) with check (true);
create policy "public all packages" on packages for all using (true) with check (true);
create policy "public all classes" on classes for all using (true) with check (true);
create policy "public all payments" on payments for all using (true) with check (true);
create policy "public all route_logs" on route_logs for all using (true) with check (true);
create policy "public all messages" on messages for all using (true) with check (true);
create policy "public all schedule_events" on schedule_events for all using (true) with check (true);
